#!/bin/bash

# $1 GeneIDs file generated by the peakAnno.R script
# $2 The <basename>peaks.xls file obtained with macs
# It extracts pertinent values and print the result

echo $1
echo $2

if [ ! $# -eq 2 ]; then
        echo Invalid number of arguments
else
        if [ -a $1 ]; then
		if [ -a $2 ]; then
			# Extract relevant infos from results
			cat $1 | awk '{print $6}' > part1.tmp # Emsembl identifier
			cat $1 | awk '{print $9}' > part2.tmp # Location of feature (upstream, inside, etc...)
			cat $1 | awk '{print $10}' > part3.tmp # Distance from feature
			grep chr $2 | cut -f6 > part4.tmp # Number of tags
			cat $1 | awk '{print $13}' > part5.tmp # Gene Symbol
			cat $1 | awk '{print $15, $16, $17, $18, $19, $20, $21, $22}' > part6.tmp # Gene Name
			cat $1 | awk '{print $14}' > part7.tmp # RefSeq

			# Print merged data
			paste *.tmp 

			# Clean up
			rm *.tmp
		else
			echo Invalid file name $2
		fi
        else
                echo Invalid file name $1
        fi
fi
