#!/bin/bash

# This script takes a GeneIDs file generated by the peakAnno.R scripts as argument
# It extracts pertinent values and print the result

if [ ! $# -eq 1 ]; then
        echo Invalid number of arguments
else
        if [ -a $1 ]; then
		# Extract relevant infos from results
		cat $1 | awk '{print $6}' > part1.tmp # Emsembl identifier
		cat $1 | awk '{print $9}' > part2.tmp # Location of feature (upstream, inside, etc...)
		cat $1 | awk '{print $10}' > part3.tmp # Distance from feature
		grep chr IRF3d1.unique_peaks.xls | cut -f6 > part4.tmp # Number of tags
		cat $1 | awk '{print $13}' > part5.tmp # Gene Symbol
		cat $1 | awk '{print $15, $16, $17, $18, $19, $20, $21, $22}' > part6.tmp # Gene Name
		cat $1 | awk '{print $14}' > part7.tmp # RefSeq

		# Print merged data
		paste *.tmp 

		# Clean up
		rm *.tmp
        else
                echo Invalid file name
        fi
fi
